### ISSUE TITLE
[Suggestion] Email template or translation

### ISSUE THREAD

**Issue by Draky50110** [wilminator/dokuwiki-plugin-twofactoremail#3]
Hello.
Would it be possible to have a separate e-mail template that could be modified ?
Or maybe at list a possibility to translate e-mail and subject of the e-mail ?
Thanks :)

**Comment by wilminator** [comment]
I have just pushed an update to implement this.  You will need to update both the main module and this one for it to work.  Please let me know if this works for you.

Also, I have added and removed some of the items in the English language file.  If you find that something is missing on screen, it is probably missing a matching entry in the French language file.

**Comment by Draky50110** [comment]
Ok, it's in the config options but so many problems lol

First : if I choose two factor admin link, I got this : 

![image](https://user-images.githubusercontent.com/1558487/42019898-9df426f4-7ab6-11e8-9d4a-2cb386385f81.png)

Second : can't activate e-mail code because... it's a loop !
I choose to activate but I got this message : 

> The email address associated with this account has changed. OTP codes through this account are disabled until the email account is verified again.

But I never receive any mail and of course I NEVER changed my email address.

I f I logout I can login without twofactor email and in "two factor settings" the checkbox is checked as if I was using it but I can't...

Maybe main problem is it doesn't see that my email is the same...

**Comment by wilminator** [comment]
I'm sending over a patch file for the French lang.php file- I added three
new items that have no match in the current version.  This patch places the
English text in for now, but you will at least be able to see something.

I'm researching why you would have the loop.  I will get back to you when I
have a better idea what is happening.

Mike

**Comment by wilminator** [comment]
Hmm... It does not like my patch files....  I have attached it as a text file.  Also, I have found what I believe is the problem with the email address rejection.  I think I copied my other email module's code in and did not clean it up properly.  I'm pushing that change out now.  If you supply a patch for the French files, I will add it in as well.
[2FAEmail.txt](https://github.com/wilminator/dokuwiki-plugin-twofactoremail/files/2146432/2FAEmail.txt)

**Comment by wilminator** [comment]
Okay, I have pushed a fix.  Please let me know how it works for you.  I failed to check if your email had already been verified before checking if it had changed.   This caused it to always be turned off before you even had a chance to turn it on.

**Comment by Draky50110** [comment]
I added the 2 new keys in fr/lang.php, can be copy/paste here : [https://gilles.wittezaele.fr/paste/?bd9be2ca377f2db9#0S+LSThfhqxqWt3ovfSOeWjtvUe7W/qYJicNRQpf3E8=](https://gilles.wittezaele.fr/paste/?bd9be2ca377f2db9#0S+LSThfhqxqWt3ovfSOeWjtvUe7W/qYJicNRQpf3E8=)

Now, setting up OTP by email is ok : it sends me the 1st verif code.

But another problem : even if enabled (bock checked), login just asks me ident/password but it does go to 2FA screen so I'm identified without using OTP.

**Comment by wilminator** [comment]
I'm trying to understand the flow of events.  You log in with your username and password but not with a token.  Instead of getting the new screen asking for your OTP code, you are directed to the twofactor profile page.  Is this correct?

**Comment by Draky50110** [comment]
I log in with ident and password but there is no more screen asking for email code and code is not sent in my email.
But I receive the mail of successful login.
I'm redirected to the home page of the wiki.

**Comment by Draky50110** [comment]
By the way, the problem with admin page is ok now ;), I just updated both core plugin and email plugin.

**Comment by wilminator** [comment]
I found en error with the email module that made it not available for the login, so you would be logged in because there were no other options.  I released an update today.  Please update and let me know if it works for you.

**Comment by Draky50110** [comment]
Still not working : I'm identified without asking for code.
Also : "notification when success login" is NOT checked, I'm receiving email for successful login.

**Comment by wilminator** [comment]
Thanks. I'm looking into it.

**Comment by wilminator** [comment]
What would help at this point is a debug log.  This is a new setting in the
configuration.  If you would produce a Debug+ log for me while logging in,
I should be able to see what's happening.  Please note that the Debug+ will
provide me with trace dumps and session data that would normally contain
sensitive data, so you may want to review the data before sending it.
Please email it to me directly at michael dot wilmes at gmail dot com if
you would; that will be a huge help.
Greetings,
Mike

**Comment by Draky50110** [comment]
No problem, do you mean debug info like described here : https://www.dokuwiki.org/devel:debugging ?
EDIT : done, sent by email

**Comment by wilminator** [comment]
The problem was with the main twofactor module (I think).  My update is at https://github.com/wilminator/dokuwiki-plugin-twofactor/issues/9

**Comment by Draky50110** [comment]
I updated and it seems to work now, except one error in admin panel listing users.
Here is a screenshot : 
![2fa_admin](https://user-images.githubusercontent.com/1558487/42747520-017b0934-88dd-11e8-958d-9c2b71aa64ea.png)

**Comment by wilminator** [comment]
Thanks. I will look into it. I'm going to close the other ticket and open
this as a new issue.

**Comment by Draky50110** [comment]
:+1:
